import createSymbolIcon from './createSymbolIcon';

// Material Symbols replacements for the @material-ui/icons used by the app.
// Names mirror the MUI icons; "Outlined" MUI icons map to FILL 0, filled ones
// to FILL 1 (M3: filled = active/emphasised).

const outlined = (name) => createSymbolIcon(name);
const filled = (name) => createSymbolIcon(name, { fill: 1 });

export const ArchiveOutlined = outlined('archive');
export const AssignmentOutlined = outlined('assignment');
export const AttachFile = outlined('attach_file');
export const AudiotrackOutlined = outlined('music_note');
export const BugReport = filled('bug_report');
export const Brightness4 = outlined('dark_mode');
export const Build = filled('build');
export const Cached = outlined('cached');
export const CameraRoll = filled('camera_roll');
export const Check = outlined('check');
export const CheckBox = filled('check_box');
export const CheckBoxOutlineBlank = outlined('check_box_outline_blank');
export const CheckCircle = filled('check_circle');
export const CheckCircleOutline = outlined('check_circle');
export const Close = outlined('close');
export const CodeOutlined = outlined('code');
export const Collections = filled('photo_library');
export const Computer = outlined('computer');
export const DateRangeOutlined = outlined('date_range');
export const Delete = outlined('delete');
export const DescriptionOutlined = outlined('description');
export const DesktopMac = outlined('desktop_mac');
export const Email = outlined('mail');
export const Error = filled('error');
export const ErrorOutline = outlined('error');
export const ExpandLess = outlined('keyboard_arrow_up');
export const ExpandMore = outlined('keyboard_arrow_down');
export const FiberManualRecord = filled('fiber_manual_record');
export const FileCopy = outlined('file_copy');
export const FilterList = outlined('filter_list');
export const FlashOn = filled('bolt');
export const FlipToBack = outlined('flip_to_back');
export const Folder = filled('folder');
export const FolderOutlined = outlined('folder');
export const FolderSpecial = filled('folder_special');
export const GetApp = outlined('download');
export const Home = outlined('home');
export const HourglassFull = filled('hourglass');
export const ImageOutlined = outlined('image');
export const IndeterminateCheckBox = filled('indeterminate_check_box');
export const Info = filled('info');
export const InsertDriveFileOutlined = outlined('draft');
export const Keyboard = outlined('keyboard');
export const KeyboardArrowDown = outlined('keyboard_arrow_down');
export const KeyboardArrowRight = outlined('keyboard_arrow_right');
export const ListAlt = outlined('list_alt');
export const LiveHelp = outlined('live_help');
export const Lock = filled('lock');
export const Memory = outlined('memory');
export const MovieOutlined = outlined('movie');
export const PhoneAndroid = outlined('mobile');
export const PlayArrow = filled('play_arrow');
export const Power = outlined('power');
export const RadioButtonChecked = outlined('radio_button_checked');
export const Refresh = outlined('refresh');
export const Replay = outlined('replay');
export const SdStorage = outlined('sd_card');
export const Search = outlined('search');
export const Send = filled('send');
export const Settings = outlined('settings');
export const SettingsOverscan = outlined('settings_overscan');
export const Smartphone = outlined('mobile');
export const StarRounded = filled('star');
export const Storage = outlined('storage');
export const SwapHoriz = outlined('swap_horiz');
export const SystemUpdate = outlined('system_update_alt');
export const Tab = outlined('tab');
export const ThumbUp = filled('thumb_up');
export const ToggleOff = outlined('toggle_off');
export const TouchApp = outlined('touch_app');
export const Tune = outlined('tune');
export const Usb = outlined('usb');
export const ViewList = outlined('view_list');
export const Warning = filled('warning');
