export const styles = (theme) => ({
  root: {
    '& .MuiDialog-paper': {
      borderRadius: 14,
      border: `1px solid ${theme.palette.fileExplorerThinLineDividerColor}`,
      boxShadow: '0 20px 70px rgba(0, 0, 0, 0.28)',
      overflow: 'hidden',
    },
  },
  titleRow: {
    display: 'flex',
    alignItems: 'center',
    gap: 12,
  },
  statusIcon: {
    display: 'grid',
    placeItems: 'center',
    width: 38,
    height: 38,
  },
  successIcon: {
    color: '#2e9b5f',
    fontSize: 30,
  },
  errorIcon: {
    color: theme.palette.snackbar.error,
    fontSize: 30,
  },
  title: {
    display: 'block',
    color: theme.palette.text.primary,
    fontSize: 18,
    fontWeight: 700,
    lineHeight: 1.25,
  },
  itemCount: {
    display: 'block',
    marginTop: 3,
    color: theme.palette.text.secondary,
    fontSize: 12,
    fontWeight: 500,
  },
  routeCard: {
    display: 'grid',
    gridTemplateColumns: '1fr auto 1fr',
    alignItems: 'center',
    gap: 12,
    padding: '12px 14px',
    border: `1px solid ${theme.palette.fileExplorerThinLineDividerColor}`,
    borderRadius: 10,
    background: theme.palette.statusSurface,
    color: theme.palette.text.primary,
    fontSize: 13,
    fontWeight: 700,
    '& span:first-child': { textAlign: 'right' },
    '& svg': { color: theme.palette.secondary.main },
  },
  steps: {
    display: 'grid',
    gridTemplateColumns: 'repeat(3, 1fr)',
    gap: 8,
    margin: '18px 0',
    padding: 0,
    listStyle: 'none',
  },
  step: {
    display: 'flex',
    alignItems: 'center',
    gap: 7,
    minWidth: 0,
    color: theme.palette.text.secondary,
    fontSize: 12,
    fontWeight: 600,
  },
  stepMarker: {
    display: 'grid',
    flex: '0 0 auto',
    placeItems: 'center',
    width: 22,
    height: 22,
    border: `1px solid ${theme.palette.fileExplorerThinLineDividerColor}`,
    borderRadius: '50%',
    background: theme.palette.background.paper,
    fontSize: 11,
    '& svg': { fontSize: 18 },
  },
  stepActive: {
    color: theme.palette.text.primary,
    '& $stepMarker': {
      borderColor: theme.palette.secondary.main,
      color: theme.palette.secondary.main,
      boxShadow: `0 0 0 3px ${theme.palette.selectionBg}`,
    },
  },
  stepComplete: {
    color: theme.palette.text.primary,
    '& $stepMarker': {
      borderColor: 'transparent',
      color: '#2e9b5f',
    },
  },
  progressBlock: {
    padding: '2px 0 4px',
  },
  progressHeader: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 16,
    marginBottom: 9,
    color: theme.palette.text.primary,
    fontSize: 13,
    '& span': {
      minWidth: 0,
      overflow: 'hidden',
      whiteSpace: 'nowrap',
      textOverflow: 'ellipsis',
    },
  },
  progressMeta: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    gap: 12,
    marginTop: 8,
    color: theme.palette.text.secondary,
    fontSize: 11,
  },
  speedContainer: {
    display: 'inline-flex',
    alignItems: 'baseline',
    gap: 4,
    fontVariantNumeric: 'tabular-nums',
    fontFeatureSettings: '"tnum"',
    userSelect: 'none',
  },
  speedValue: {
    fontVariantNumeric: 'tabular-nums',
    fontFeatureSettings: '"tnum"',
    fontWeight: 600,
    minWidth: 46,
    textAlign: 'right',
    display: 'inline-block',
    letterSpacing: '0.02em',
  },
  speedUnit: {
    fontSize: 11,
    fontWeight: 500,
    opacity: 0.85,
  },
  errorBox: {
    padding: '12px 14px',
    border: `1px solid ${theme.palette.snackbar.error}`,
    borderRadius: 9,
    background: 'rgba(243, 57, 80, 0.1)',
    color: theme.palette.text.primary,
    fontSize: 13,
    lineHeight: 1.45,
  },
  activityRow: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 12,
    minHeight: 28,
    marginTop: 14,
    color: theme.palette.text.secondary,
    fontSize: 10,
  },
  diagnosticId: {
    marginLeft: 'auto',
    fontFamily: 'ui-monospace, SFMono-Regular, Menlo, monospace',
    whiteSpace: 'nowrap',
  },
  actions: {
    padding: '10px 24px 18px',
  },
  '@media (prefers-reduced-motion: reduce)': {
    root: {
      '& *': {
        animationDuration: '0.01ms !important',
        transitionDuration: '0.01ms !important',
      },
    },
  },
});
