import {
  alphaHex,
  m3Elevation,
  m3Motion,
  m3Shape,
  m3State,
  m3Type,
} from '../../../styles/m3/tokens';

export const styles = (theme) => {
  const { m3 } = theme.palette;

  return {
    root: {
      position: 'sticky',
      top: 0,
      zIndex: 30,
      display: 'flex',
      alignItems: 'center',
      padding: '8px 12px',
      backgroundColor: theme.palette.tableHeaderFooterBgColor,
      borderBottom: `1px solid ${theme.palette.fileExplorerThinLineDividerColor}`,
    },
    // M3 search bar (Compose SearchBarTokens): full corners, surface
    // container high, onSurface leading icon, bodyLarge input. 48dp tall
    // here (desktop density) instead of 56dp.
    inputShell: {
      position: 'relative',
      display: 'flex',
      alignItems: 'center',
      width: '100%',
      height: 48,
      padding: '0 4px 0 16px',
      boxSizing: 'border-box',
      borderRadius: 24,
      backgroundColor: m3.surfaceContainerHigh,
      transition: `border-radius ${m3Motion.fastSpatial}, box-shadow ${m3Motion.defaultEffects}`,
      '&:hover:not($inputShellOpen)': {
        boxShadow: `inset 0 0 0 100px ${alphaHex(m3.onSurface, m3State.hover)}`,
      },
      '&:focus-within': {
        boxShadow: `inset 0 0 0 2px ${m3.secondary}`,
      },
      '@media (prefers-reduced-motion: reduce)': {
        transition: 'none',
      },
    },
    // docked search view open below: square bottom corners, shared surface
    inputShellOpen: {
      borderRadius: `${m3Shape.extraLarge}px ${m3Shape.extraLarge}px 0 0`,
      boxShadow: m3Elevation.level2,
      '&:focus-within': {
        boxShadow: m3Elevation.level2,
      },
    },
    searchIcon: {
      flex: '0 0 auto',
      marginRight: 16,
      fontSize: 24,
      color: m3.onSurface,
    },
    input: {
      ...m3Type.bodyLarge,
      flex: '1 1 auto',
      minWidth: 0,
      color: m3.onSurface,
      fontFamily: 'inherit',
      '& input': {
        padding: 0,
        '&::placeholder': { color: m3.onSurfaceVariant, opacity: 1 },
      },
    },
    progress: {
      flex: '0 0 auto',
      margin: '0 4px',
      color: m3.primary,
    },
    // M3 standard icon buttons (40dp)
    clearButton: {
      flex: '0 0 auto',
      width: 40,
      height: 40,
      padding: 8,
      color: m3.onSurfaceVariant,
      '&:hover': {
        backgroundColor: alphaHex(m3.onSurfaceVariant, m3State.hover),
      },
      '& svg': { fontSize: 24 },
    },
    filterDivider: {
      flex: '0 0 auto',
      width: 1,
      height: 24,
      margin: '0 4px',
      backgroundColor: m3.outlineVariant,
    },
    filterActions: {
      display: 'flex',
      flex: '0 0 auto',
      alignItems: 'center',
      gap: 0,
    },
    filterButton: {
      position: 'relative',
      flex: '0 0 auto',
      width: 40,
      height: 40,
      padding: 8,
      borderRadius: 20,
      color: m3.onSurfaceVariant,
      transition: `color ${m3Motion.defaultEffects}, background-color ${m3Motion.defaultEffects}`,
      '&:hover': {
        backgroundColor: alphaHex(m3.onSurfaceVariant, m3State.hover),
      },
      '&:focus-visible': {
        outline: `3px solid ${m3.secondary}`,
      },
      '& svg': { fontSize: 24 },
      '@media (prefers-reduced-motion: reduce)': { transition: 'none' },
    },
    // toggle icon button, selected: secondary container
    filterButtonActive: {
      color: m3.onSecondaryContainer,
      backgroundColor: m3.secondaryContainer,
      '&:hover': { backgroundColor: m3.secondaryContainer },
    },
    filterActiveDot: {
      position: 'absolute',
      top: 6,
      right: 6,
      width: 6,
      height: 6,
      borderRadius: '50%',
      backgroundColor: m3.error,
    },
    filterCountBadge: {
      ...m3Type.labelSmall,
      position: 'absolute',
      top: 2,
      right: 2,
      minWidth: 16,
      height: 16,
      padding: '0 4px',
      boxSizing: 'border-box',
      borderRadius: 8,
      color: m3.onError,
      backgroundColor: m3.error,
      lineHeight: '16px',
      textAlign: 'center',
    },
    // ---- M3 filter popovers (date / type) ----
    dateFilterPaper: {
      width: 380,
      marginTop: 8,
      overflow: 'hidden',
      borderRadius: m3Shape.extraLarge,
      color: m3.onSurface,
      backgroundColor: m3.surfaceContainerHigh,
      boxShadow: m3Elevation.level3,
    },
    typeFilterPaper: {
      width: 360,
      marginTop: 8,
      overflow: 'hidden',
      borderRadius: m3Shape.extraLarge,
      color: m3.onSurface,
      backgroundColor: m3.surfaceContainerHigh,
      boxShadow: m3Elevation.level3,
    },
    dateFilterContent: {
      padding: '20px 20px 16px',
    },
    dateFilterHeader: {
      display: 'flex',
      alignItems: 'center',
      gap: 14,
      marginBottom: 18,
      '& h3': {
        ...m3Type.titleLarge,
        margin: 0,
        color: m3.onSurface,
      },
      '& p': {
        ...m3Type.bodyMedium,
        margin: '2px 0 0',
        color: m3.onSurfaceVariant,
      },
    },
    headerShape: {
      color: m3.primaryContainer,
    },
    headerIcon: {
      color: m3.onPrimaryContainer,
    },
    sectionLabel: {
      ...m3Type.labelLarge,
      display: 'block',
      margin: '0 0 8px 4px',
      color: m3.onSurfaceVariant,
    },
    // M3 segmented button
    segmented: {
      display: 'flex',
      marginBottom: 6,
    },
    segment: {
      ...m3Type.labelLarge,
      display: 'flex',
      flex: 1,
      alignItems: 'center',
      justifyContent: 'center',
      gap: 6,
      height: 40,
      padding: '0 12px',
      border: `1px solid ${m3.outline}`,
      backgroundColor: 'transparent',
      color: m3.onSurface,
      fontFamily: 'inherit',
      cursor: 'pointer',
      transition: `background-color ${m3Motion.defaultEffects}`,
      '&:first-child': { borderRadius: '20px 0 0 20px' },
      '&:last-child': { borderRadius: '0 20px 20px 0', marginLeft: -1 },
      '&:hover:not(:disabled)': {
        backgroundColor: alphaHex(m3.onSurface, m3State.hover),
      },
      '&:disabled': {
        cursor: 'default',
        color: alphaHex(m3.onSurface, m3State.disabledContent),
        borderColor: alphaHex(m3.onSurface, 0.12),
      },
    },
    segmentSelected: {
      backgroundColor: m3.secondaryContainer,
      color: m3.onSecondaryContainer,
      '&:hover:not(:disabled)': { backgroundColor: m3.secondaryContainer },
    },
    dateFilterNotice: {
      ...m3Type.bodySmall,
      margin: '0 0 14px 4px',
      color: m3.onSurfaceVariant,
    },
    // M3 filter / suggestion chips
    chips: {
      display: 'flex',
      flexWrap: 'wrap',
      gap: 8,
      margin: '4px 0 18px',
    },
    chip: {
      ...m3Type.labelLarge,
      display: 'inline-flex',
      alignItems: 'center',
      gap: 6,
      height: 32,
      padding: '0 14px',
      border: `1px solid ${m3.outlineVariant}`,
      borderRadius: m3Shape.small,
      backgroundColor: 'transparent',
      color: m3.onSurfaceVariant,
      fontFamily: 'inherit',
      cursor: 'pointer',
      transition: `background-color ${m3Motion.defaultEffects}, border-radius ${m3Motion.fastSpatial}`,
      '&:hover': {
        backgroundColor: alphaHex(m3.onSurfaceVariant, m3State.hover),
      },
      '&:active': { borderRadius: 16 },
    },
    chipSelected: {
      borderColor: 'transparent',
      backgroundColor: m3.secondaryContainer,
      color: m3.onSecondaryContainer,
      '&:hover': { backgroundColor: m3.secondaryContainer },
    },
    chipCount: {
      ...m3Type.labelLarge,
      opacity: 0.7,
      fontVariantNumeric: 'tabular-nums',
    },
    typeFilterList: {
      display: 'flex',
      flexWrap: 'wrap',
      gap: 8,
      maxHeight: 260,
      overflowY: 'auto',
      overscrollBehavior: 'contain',
    },
    typeFilterEmpty: {
      ...m3Type.bodyMedium,
      margin: 0,
      padding: '20px 0',
      color: m3.onSurfaceVariant,
      textAlign: 'center',
    },
    dateFilterError: {
      ...m3Type.bodySmall,
      margin: '8px 0 0 4px',
      color: m3.error,
    },
    dateFilterActions: {
      display: 'flex',
      alignItems: 'center',
      justifyContent: 'space-between',
      marginTop: 20,
      '& > div': { display: 'flex', gap: 8 },
    },
    // M3 docked search view (Compose SearchViewTokens): surface container
    // high, extra large corners, outline divider under the search field
    resultsPanel: {
      position: 'absolute',
      top: 56,
      left: 12,
      right: 12,
      overflow: 'hidden',
      borderRadius: `0 0 ${m3Shape.extraLarge}px ${m3Shape.extraLarge}px`,
      backgroundColor: m3.surfaceContainerHigh,
      borderTop: `1px solid ${m3.outline}`,
      boxShadow: m3Elevation.level2,
      clipPath: 'inset(0 -20px -20px -20px)',
    },
    resultsMeta: {
      ...m3Type.bodySmall,
      display: 'flex',
      alignItems: 'center',
      justifyContent: 'space-between',
      gap: 12,
      minHeight: 36,
      padding: '8px 16px 4px',
      color: m3.onSurfaceVariant,
    },
    resultsScope: {
      overflow: 'hidden',
      textOverflow: 'ellipsis',
      whiteSpace: 'nowrap',
    },
    resultsList: {
      maxHeight: 360,
      paddingBottom: 8,
      overflowY: 'auto',
      overscrollBehavior: 'contain',
    },
    // M3 two-line list item
    result: {
      display: 'flex',
      alignItems: 'center',
      gap: 16,
      width: '100%',
      minHeight: 56,
      padding: '8px 16px',
      boxSizing: 'border-box',
      color: m3.onSurface,
      background: 'none',
      border: 0,
      textAlign: 'left',
      fontFamily: 'inherit',
      cursor: 'pointer',
      outline: 'none',
      '&:focus-visible': {
        boxShadow: `inset 0 0 0 3px ${m3.secondary}`,
      },
    },
    resultActive: {
      backgroundColor: alphaHex(m3.onSurface, m3State.hover),
    },
    resultIcon: {
      flex: '0 0 auto',
      width: 32,
      height: 32,
      objectFit: 'contain',
    },
    resultText: {
      display: 'flex',
      flex: '1 1 auto',
      minWidth: 0,
      flexDirection: 'column',
    },
    resultName: {
      ...m3Type.bodyLarge,
      overflow: 'hidden',
      color: m3.onSurface,
      whiteSpace: 'nowrap',
      textOverflow: 'ellipsis',
      '& mark': {
        padding: 0,
        borderRadius: 2,
        color: m3.onPrimaryContainer,
        backgroundColor: m3.primaryContainer,
      },
    },
    resultPath: {
      ...m3Type.bodyMedium,
      overflow: 'hidden',
      color: m3.onSurfaceVariant,
      whiteSpace: 'nowrap',
      textOverflow: 'ellipsis',
    },
    folderIndicator: {
      flex: '0 0 auto',
      fontSize: 24,
      color: m3.onSurfaceVariant,
    },
    emptyResult: {
      ...m3Type.bodyMedium,
      padding: '24px 16px 28px',
      color: m3.onSurfaceVariant,
      textAlign: 'center',
    },
    limitNotice: {
      ...m3Type.bodySmall,
      padding: '8px 16px 12px',
      color: m3.onSurfaceVariant,
    },
  };
};
