export const styles = (theme) => ({
  root: {
    position: 'sticky',
    top: 0,
    zIndex: 30,
    display: 'flex',
    alignItems: 'center',
    minHeight: 50,
    padding: '7px 12px',
    backgroundColor: theme.palette.tableHeaderFooterBgColor,
    borderBottom: `1px solid ${theme.palette.fileExplorerThinLineDividerColor}`,
  },
  inputShell: {
    display: 'flex',
    alignItems: 'center',
    width: '100%',
    height: 36,
    padding: '0 7px 0 10px',
    borderRadius: 9,
    backgroundColor: theme.palette.background.paper,
    border: `1px solid ${theme.palette.divider}`,
    transition: 'border-color 160ms ease, box-shadow 160ms ease',
    '&:focus-within': {
      borderColor: theme.palette.selectionBorder,
      boxShadow: `0 0 0 3px ${theme.palette.focusRing}`,
    },
    '@media (prefers-reduced-motion: reduce)': {
      transition: 'none',
    },
  },
  searchIcon: {
    flex: '0 0 auto',
    marginRight: 8,
    fontSize: 19,
    color: theme.palette.text.secondary,
  },
  input: {
    flex: '1 1 auto',
    minWidth: 0,
    fontSize: 13,
    color: theme.palette.text.primary,
    '& input': { padding: 0 },
  },
  progress: {
    flex: '0 0 auto',
    margin: '0 7px',
    color: theme.palette.secondary.main,
  },
  clearButton: {
    flex: '0 0 auto',
    padding: 4,
    color: theme.palette.text.secondary,
    '&:hover': {
      color: theme.palette.text.primary,
      backgroundColor: theme.palette.toolbarButtonHover,
    },
    '& svg': { fontSize: 17 },
  },
  resultsPanel: {
    position: 'absolute',
    top: 45,
    left: 12,
    right: 12,
    overflow: 'hidden',
    borderRadius: 10,
    backgroundColor: theme.palette.background.paper,
    border: `1px solid ${theme.palette.divider}`,
    boxShadow: theme.shadows[8],
  },
  resultsMeta: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    minHeight: 34,
    padding: '7px 11px',
    color: theme.palette.text.secondary,
    backgroundColor: theme.palette.statusSurface,
    borderBottom: `1px solid ${theme.palette.divider}`,
    fontSize: 11,
    fontWeight: 600,
  },
  resultsList: {
    maxHeight: 350,
    overflowY: 'auto',
    overscrollBehavior: 'contain',
  },
  result: {
    display: 'flex',
    alignItems: 'center',
    width: '100%',
    minHeight: 50,
    padding: '6px 10px',
    color: theme.palette.text.primary,
    background: 'none',
    border: 0,
    borderBottom: `1px solid ${theme.palette.divider}`,
    textAlign: 'left',
    cursor: 'default',
    outline: 'none',
    '&:last-child': { borderBottom: 0 },
    '&:hover, &:focus-visible': {
      backgroundColor: theme.palette.selectionHover,
    },
    '&:focus-visible': {
      boxShadow: `inset 0 0 0 2px ${theme.palette.selectionBorder}`,
    },
  },
  resultActive: {
    backgroundColor: `${theme.palette.selectionBg} !important`,
  },
  resultIcon: {
    flex: '0 0 auto',
    width: 29,
    height: 29,
    marginRight: 10,
    objectFit: 'contain',
  },
  resultText: {
    display: 'flex',
    flex: '1 1 auto',
    minWidth: 0,
    flexDirection: 'column',
  },
  resultName: {
    overflow: 'hidden',
    color: theme.palette.text.primary,
    fontSize: 13,
    fontWeight: 600,
    whiteSpace: 'nowrap',
    textOverflow: 'ellipsis',
    '& mark': {
      padding: 0,
      borderRadius: 2,
      color: theme.palette.text.primary,
      backgroundColor: theme.palette.selectionBg,
      boxShadow: `inset 0 -2px 0 ${theme.palette.selectionBorder}`,
    },
  },
  resultPath: {
    overflow: 'hidden',
    marginTop: 2,
    color: theme.palette.text.secondary,
    fontSize: 10,
    whiteSpace: 'nowrap',
    textOverflow: 'ellipsis',
  },
  folderIndicator: {
    flex: '0 0 auto',
    marginLeft: 9,
    fontSize: 16,
    color: theme.palette.text.secondary,
  },
  emptyResult: {
    padding: '24px 12px',
    color: theme.palette.text.secondary,
    textAlign: 'center',
    fontSize: 12,
  },
  limitNotice: {
    padding: '7px 11px',
    color: theme.palette.text.secondary,
    backgroundColor: theme.palette.statusSurface,
    borderTop: `1px solid ${theme.palette.divider}`,
    fontSize: 10,
  },
});
