export const styles = (theme) => ({
  root: {
    display: 'grid',
    gridTemplateColumns: 'minmax(90px, auto) 1fr minmax(0, auto)',
    alignItems: 'center',
    gap: 12,
    padding: '0 12px',
    width: '100%',
    height: 34,
    background: theme.palette.statusSurface,
    borderTop: `1px solid ${theme.palette.fileExplorerThinLineDividerColor}`,
    color: theme.palette.text.secondary,
    fontSize: 11,
    overflow: 'hidden',
  },
  deviceBlock: {
    display: 'flex',
    alignItems: 'center',
    gap: 6,
    minWidth: 0,
    fontWeight: 700,
    color: theme.palette.secondary.main,
    '& svg': { fontSize: 16 },
    '& span': {
      overflow: 'hidden',
      whiteSpace: 'nowrap',
      textOverflow: 'ellipsis',
    },
  },
  metricsBlock: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 12,
    minWidth: 0,
    whiteSpace: 'nowrap',
  },
  slotWrapper: {
    display: 'inline-flex',
    alignItems: 'center',
    justifyContent: 'center',
    minWidth: '0.6em',
    verticalAlign: 'baseline',
  },
  totalMetric: {
    display: 'inline-flex',
    alignItems: 'center',
    gap: 4,
    fontWeight: 700,
    color: theme.palette.text.primary,
  },
  metric: {
    display: 'inline-flex',
    alignItems: 'center',
    gap: 4,
    '& svg': { fontSize: 14 },
  },
  contextBlock: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'flex-end',
    gap: 8,
    minWidth: 0,
  },
  selectionMetric: {
    display: 'inline-flex',
    alignItems: 'center',
    gap: 4,
    color: theme.palette.secondary.main,
    fontWeight: 700,
    '& svg': { fontSize: 15 },
  },
  clipboardMetric: {
    display: 'inline-flex',
    alignItems: 'center',
    gap: 4,
    whiteSpace: 'nowrap',
    '& svg': { fontSize: 14 },
  },
  transferButton: {
    minHeight: 26,
    padding: '3px 9px',
    borderRadius: 7,
    textTransform: 'none',
    fontSize: 11,
    fontWeight: 700,
    boxShadow: 'none',
    whiteSpace: 'nowrap',
    '&:focus-visible': {
      outline: `2px solid ${theme.palette.focusRing}`,
      outlineOffset: 2,
    },
    '& .MuiButton-startIcon': {
      marginRight: 5,
      '& svg': { fontSize: 16 },
    },
  },
  transferCount: {
    display: 'inline-grid',
    placeItems: 'center',
    minWidth: 18,
    height: 18,
    marginLeft: 7,
    padding: '0 5px',
    borderRadius: 9,
    background: 'rgba(255, 255, 255, 0.2)',
    fontSize: 10,
  },
  '@media (max-width: 760px)': {
    metricsBlock: { justifyContent: 'flex-start' },
    metric: { display: 'none' },
  },
});
