import { tableCellFileExplorerTableRowsRender } from './FileExplorerTableBodyListRender';

export const styles = (theme) => ({
  emptyTableRowWrapper: {},
  tableCell: {
    ...tableCellFileExplorerTableRowsRender,
    borderBottom: 'none',
    padding: 0,
  },
  emptyPaneContainer: {
    position: 'relative',
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'center',
    minHeight: 460,
    padding: '40px 24px',
    textAlign: 'center',
    overflow: 'hidden',
  },
  contentWrapper: {
    position: 'relative',
    zIndex: 1,
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    maxWidth: 620,
    width: '100%',
  },
  phoneIconBadge: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    width: 64,
    height: 64,
    borderRadius: 20,
    color: theme.palette.secondary.main,
    backgroundColor: 'rgba(25, 118, 210, 0.08)',
    boxShadow: '0 8px 24px rgba(25, 118, 210, 0.12)',
    marginBottom: 20,
    '& svg': {
      fontSize: 34,
    },
  },
  title: {
    fontWeight: 700,
    letterSpacing: '-0.025em',
    fontSize: 22,
    color: theme.palette.text.primary,
    marginBottom: 6,
  },
  subtitle: {
    fontSize: 13.5,
    color: theme.palette.text.secondary,
    maxWidth: 440,
    lineHeight: 1.45,
    marginBottom: 24,
  },
  actionsRow: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 12,
    marginBottom: 28,
  },
  primaryBtn: {
    borderRadius: 12,
    textTransform: 'none',
    fontWeight: 650,
    padding: '11px 26px',
    fontSize: 14,
    backgroundColor: theme.palette.secondary.main,
    color: '#ffffff',
    boxShadow: '0 4px 16px rgba(25, 118, 210, 0.3)',
    transition: 'all 200ms cubic-bezier(0.2, 0, 0, 1)',
    '&:hover': {
      backgroundColor: '#1565c0',
      boxShadow: '0 6px 22px rgba(25, 118, 210, 0.45)',
      transform: 'translateY(-2px)',
    },
    '&:active': {
      transform: 'translateY(0)',
      boxShadow: '0 2px 8px rgba(25, 118, 210, 0.3)',
    },
    '&.Mui-disabled': {
      backgroundColor: 'rgba(128, 128, 128, 0.2)',
      color: 'rgba(128, 128, 128, 0.5)',
      boxShadow: 'none',
    },
  },
  secondaryLinkBtn: {
    borderRadius: 12,
    textTransform: 'none',
    fontWeight: 600,
    padding: '11px 20px',
    fontSize: 14,
    color: theme.palette.text.secondary,
    transition: 'all 200ms ease',
    '&:hover': {
      color: theme.palette.secondary.main,
      backgroundColor: 'rgba(25, 118, 210, 0.08)',
      '& svg': {
        transform: 'translate(2px, -2px)',
      },
    },
    '& svg': {
      fontSize: 18,
      marginLeft: 4,
      transition: 'transform 200ms ease',
    },
  },
  diagnosticAlert: {
    display: 'inline-flex',
    alignItems: 'center',
    gap: 10,
    padding: '10px 18px',
    marginBottom: 28,
    borderRadius: 20,
    fontSize: 12.5,
    border: '1px solid rgba(255, 152, 0, 0.3)',
    color: theme.palette.text.primary,
    backgroundColor: 'rgba(255, 152, 0, 0.07)',
  },
  conflictWarningAlert: {
    display: 'inline-flex',
    alignItems: 'center',
    gap: 10,
    padding: '10px 18px',
    marginBottom: 28,
    borderRadius: 20,
    fontSize: 12.5,
    border: '1px solid rgba(243, 57, 80, 0.3)',
    color: theme.palette.snackbar.error,
    backgroundColor: 'rgba(243, 57, 80, 0.07)',
  },
  conflictSuccessAlert: {
    display: 'inline-flex',
    alignItems: 'center',
    gap: 8,
    padding: '8px 16px',
    marginBottom: 28,
    borderRadius: 20,
    fontSize: 12,
    color: theme.palette.text.secondary,
    border: `1px solid ${theme.palette.fileExplorerThinLineDividerColor}`,
    backgroundColor: 'rgba(128, 128, 128, 0.04)',
    '& svg': {
      fontSize: 16,
      color: '#2e9b5f',
    },
  },
  stepsGrid: {
    display: 'grid',
    gridTemplateColumns: 'repeat(2, 1fr)',
    gap: 12,
    width: '100%',
    textAlign: 'left',
  },
  stepItem: {
    display: 'flex',
    alignItems: 'flex-start',
    gap: 12,
    padding: '14px 16px',
    borderRadius: 14,
    border: `1px solid ${theme.palette.fileExplorerThinLineDividerColor}`,
    backgroundColor: theme.palette.background.paper,
    transition: 'all 200ms ease',
    '&:hover': {
      borderColor: theme.palette.secondary.main,
      transform: 'translateY(-2px)',
      boxShadow: '0 6px 20px rgba(0, 0, 0, 0.04)',
    },
  },
  stepIconBadge: {
    display: 'grid',
    placeItems: 'center',
    width: 34,
    height: 34,
    flex: '0 0 auto',
    borderRadius: 10,
    color: theme.palette.secondary.main,
    backgroundColor: 'rgba(25, 118, 210, 0.09)',
    '& svg': {
      fontSize: 19,
    },
  },
  stepTitle: {
    fontSize: 12.5,
    fontWeight: 650,
    color: theme.palette.text.primary,
    lineHeight: 1.35,
  },
  stepDesc: {
    fontSize: 11.5,
    marginTop: 2,
    color: theme.palette.text.secondary,
    lineHeight: 1.35,
  },
});
