export const styles = (theme) => ({
  root: {
    position: 'sticky',
    top: 0,
    zIndex: 30,
    display: 'flex',
    alignItems: 'center',
    minHeight: 50,
    padding: '7px 12px',
    backgroundColor: theme.palette.tableHeaderFooterBgColor,
    borderBottom: `1px solid ${theme.palette.fileExplorerThinLineDividerColor}`,
  },
  inputShell: {
    display: 'flex',
    alignItems: 'center',
    width: '100%',
    height: 36,
    padding: '0 7px 0 10px',
    borderRadius: 9,
    backgroundColor: theme.palette.background.paper,
    border: `1px solid ${theme.palette.divider}`,
    transition: 'border-color 160ms ease, box-shadow 160ms ease',
    '&:focus-within': {
      borderColor: theme.palette.selectionBorder,
      boxShadow: `0 0 0 3px ${theme.palette.focusRing}`,
    },
    '@media (prefers-reduced-motion: reduce)': {
      transition: 'none',
    },
  },
  searchIcon: {
    flex: '0 0 auto',
    marginRight: 8,
    fontSize: 19,
    color: theme.palette.text.secondary,
  },
  input: {
    flex: '1 1 auto',
    minWidth: 0,
    fontSize: 13,
    color: theme.palette.text.primary,
    '& input': { padding: 0 },
  },
  progress: {
    flex: '0 0 auto',
    margin: '0 7px',
    color: theme.palette.secondary.main,
  },
  clearButton: {
    flex: '0 0 auto',
    padding: 4,
    color: theme.palette.text.secondary,
    '&:hover': {
      color: theme.palette.text.primary,
      backgroundColor: theme.palette.toolbarButtonHover,
    },
    '& svg': { fontSize: 17 },
  },
  filterDivider: {
    flex: '0 0 auto',
    width: 1,
    height: 18,
    margin: '0 5px 0 3px',
    backgroundColor: theme.palette.divider,
  },
  filterActions: {
    display: 'flex',
    flex: '0 0 auto',
    alignItems: 'center',
    gap: 2,
  },
  filterButton: {
    position: 'relative',
    flex: '0 0 auto',
    padding: 5,
    borderRadius: 6,
    color: theme.palette.text.secondary,
    transition: 'color 160ms ease, background-color 160ms ease',
    '&:hover': {
      color: theme.palette.text.primary,
      backgroundColor: theme.palette.toolbarButtonHover,
    },
    '&:focus-visible': {
      boxShadow: `0 0 0 2px ${theme.palette.focusRing}`,
    },
    '& svg': { fontSize: 18 },
    '@media (prefers-reduced-motion: reduce)': { transition: 'none' },
  },
  filterButtonActive: {
    color: theme.palette.selectionBorder,
    backgroundColor: theme.palette.selectionBg,
  },
  filterActiveDot: {
    position: 'absolute',
    top: 3,
    right: 3,
    width: 5,
    height: 5,
    borderRadius: '50%',
    backgroundColor: theme.palette.selectionBorder,
    boxShadow: `0 0 0 1.5px ${theme.palette.background.paper}`,
  },
  filterCountBadge: {
    position: 'absolute',
    top: -3,
    right: -3,
    minWidth: 14,
    height: 14,
    padding: '0 3px',
    borderRadius: 7,
    color: theme.palette.background.paper,
    backgroundColor: theme.palette.selectionBorder,
    border: `1.5px solid ${theme.palette.background.paper}`,
    fontSize: 8,
    fontWeight: 800,
    lineHeight: '11px',
    textAlign: 'center',
  },
  dateFilterPaper: {
    width: 340,
    marginTop: 6,
    overflow: 'hidden',
    borderRadius: 12,
    color: theme.palette.text.primary,
    backgroundColor: theme.palette.background.paper,
    border: `1px solid ${theme.palette.divider}`,
    boxShadow: theme.shadows[10],
  },
  typeFilterPaper: {
    width: 310,
    marginTop: 6,
    overflow: 'hidden',
    borderRadius: 12,
    color: theme.palette.text.primary,
    backgroundColor: theme.palette.background.paper,
    border: `1px solid ${theme.palette.divider}`,
    boxShadow: theme.shadows[10],
  },
  dateFilterContent: {
    padding: 16,
  },
  dateFilterHeader: {
    display: 'flex',
    alignItems: 'flex-start',
    marginBottom: 10,
    '& > svg': {
      flex: '0 0 auto',
      margin: '2px 10px 0 0',
      color: theme.palette.selectionBorder,
      fontSize: 21,
    },
    '& h3': {
      margin: 0,
      color: theme.palette.text.primary,
      fontSize: 15,
      fontWeight: 700,
      lineHeight: 1.35,
    },
    '& p': {
      margin: '3px 0 0',
      color: theme.palette.text.secondary,
      fontSize: 11,
      lineHeight: 1.4,
    },
  },
  dateFilterField: {
    '& .MuiOutlinedInput-root': { borderRadius: 8 },
  },
  dateFilterNotice: {
    margin: '3px 0 8px',
    color: theme.palette.text.secondary,
    fontSize: 10.5,
    lineHeight: 1.45,
  },
  typeFilterList: {
    maxHeight: 270,
    margin: '4px -6px 0',
    overflowY: 'auto',
    overscrollBehavior: 'contain',
  },
  typeFilterOption: {
    display: 'flex',
    width: '100%',
    minHeight: 36,
    margin: 0,
    padding: '0 6px',
    borderRadius: 7,
    '&:hover': { backgroundColor: theme.palette.selectionHover },
    '& .MuiCheckbox-root': { padding: 6 },
    '& .MuiFormControlLabel-label': { flex: '1 1 auto', minWidth: 0 },
  },
  typeFilterOptionLabel: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    width: '100%',
    color: theme.palette.text.primary,
    fontSize: 11.5,
    fontWeight: 650,
    '& span:last-child': {
      minWidth: 24,
      color: theme.palette.text.secondary,
      fontSize: 10,
      fontWeight: 600,
      textAlign: 'right',
    },
  },
  typeFilterEmpty: {
    margin: 0,
    padding: '22px 10px',
    color: theme.palette.text.secondary,
    fontSize: 11,
    textAlign: 'center',
  },
  dateFilterDates: {
    display: 'grid',
    gridTemplateColumns: '1fr 1fr',
    gap: 10,
    '& .MuiOutlinedInput-root': { borderRadius: 8 },
    '& .MuiInputBase-input': { fontSize: 12 },
  },
  dateFilterError: {
    margin: '3px 0 0',
    color: theme.palette.error.main,
    fontSize: 10.5,
  },
  dateFilterActions: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    margin: '15px -5px -5px',
    paddingTop: 11,
    borderTop: `1px solid ${theme.palette.divider}`,
    '& > div': { display: 'flex', gap: 4 },
    '& .MuiButton-root': {
      minWidth: 0,
      borderRadius: 7,
      fontSize: 11,
      fontWeight: 700,
      textTransform: 'none',
    },
  },
  resultsPanel: {
    position: 'absolute',
    top: 45,
    left: 12,
    right: 12,
    overflow: 'hidden',
    borderRadius: 10,
    backgroundColor: theme.palette.background.paper,
    border: `1px solid ${theme.palette.divider}`,
    boxShadow: theme.shadows[8],
  },
  resultsMeta: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    minHeight: 34,
    padding: '7px 11px',
    color: theme.palette.text.secondary,
    backgroundColor: theme.palette.statusSurface,
    borderBottom: `1px solid ${theme.palette.divider}`,
    fontSize: 11,
    fontWeight: 600,
  },
  resultsList: {
    maxHeight: 350,
    overflowY: 'auto',
    overscrollBehavior: 'contain',
  },
  result: {
    display: 'flex',
    alignItems: 'center',
    width: '100%',
    minHeight: 50,
    padding: '6px 10px',
    color: theme.palette.text.primary,
    background: 'none',
    border: 0,
    borderBottom: `1px solid ${theme.palette.divider}`,
    textAlign: 'left',
    cursor: 'default',
    outline: 'none',
    '&:last-child': { borderBottom: 0 },
    '&:hover, &:focus-visible': {
      backgroundColor: theme.palette.selectionHover,
    },
    '&:focus-visible': {
      boxShadow: `inset 0 0 0 2px ${theme.palette.selectionBorder}`,
    },
  },
  resultActive: {
    backgroundColor: `${theme.palette.selectionBg} !important`,
  },
  resultIcon: {
    flex: '0 0 auto',
    width: 29,
    height: 29,
    marginRight: 10,
    objectFit: 'contain',
  },
  resultText: {
    display: 'flex',
    flex: '1 1 auto',
    minWidth: 0,
    flexDirection: 'column',
  },
  resultName: {
    overflow: 'hidden',
    color: theme.palette.text.primary,
    fontSize: 13,
    fontWeight: 600,
    whiteSpace: 'nowrap',
    textOverflow: 'ellipsis',
    '& mark': {
      padding: 0,
      borderRadius: 2,
      color: theme.palette.text.primary,
      backgroundColor: theme.palette.selectionBg,
      boxShadow: `inset 0 -2px 0 ${theme.palette.selectionBorder}`,
    },
  },
  resultPath: {
    overflow: 'hidden',
    marginTop: 2,
    color: theme.palette.text.secondary,
    fontSize: 10,
    whiteSpace: 'nowrap',
    textOverflow: 'ellipsis',
  },
  folderIndicator: {
    flex: '0 0 auto',
    marginLeft: 9,
    fontSize: 16,
    color: theme.palette.text.secondary,
  },
  emptyResult: {
    padding: '24px 12px',
    color: theme.palette.text.secondary,
    textAlign: 'center',
    fontSize: 12,
  },
  limitNotice: {
    padding: '7px 11px',
    color: theme.palette.text.secondary,
    backgroundColor: theme.palette.statusSurface,
    borderTop: `1px solid ${theme.palette.divider}`,
    fontSize: 10,
  },
});
